// src/content/iconPaths.ts
export const iconPaths: Record<string, string> = {
  nextjs: "/icons/nextjs.svg",
  react: "/icons/react.svg",
  typescript: "/icons/typescript.svg",
  javascript: "/icons/javascript.svg",
  supabase: "/icons/supabase.svg",
  postgresql: "/icons/postgresql.svg",
  nodejs: "/icons/nodejs.svg",
  express: "/icons/express.svg",
  vercel: "/icons/vercel.svg",
  github: "/icons/github.svg",
  git: "/icons/git.svg",
  tailwind: "/icons/tailwind.svg",
  vite: "/icons/vite.svg",
  redux: "/icons/redux.svg",
  firebase: "/icons/firebase.svg",
  stripe: "/icons/stripe.svg",
  docker: "/icons/docker.svg",
  linux: "/icons/linux.svg",
  threejs: "/icons/threejs.svg",
  html: "/icons/html.svg",
  css: "/icons/css.svg",
  figma: "/icons/figma.svg",
} as const;
