// content/tech.ts
export const techStack = [
  { key: "nextjs",     label: "Next.js" },
  { key: "react",      label: "React" },
  { key: "typescript", label: "TypeScript" },
  { key: "javascript", label: "JavaScript" },
  { key: "supabase",   label: "Supabase" },
  { key: "postgresql", label: "PostgreSQL" },
  { key: "nodejs",     label: "Node.js" },
  { key: "express",    label: "Express.js" },
  { key: "vercel",     label: "Vercel" },
  { key: "github",     label: "GitHub" },
  { key: "git",        label: "Git" },
  { key: "tailwind",   label: "Tailwind CSS" },
  { key: "vite",       label: "Vite" },
  { key: "redux",      label: "Redux Toolkit" }, // uses Redux logo
  { key: "firebase",   label: "Firebase" },
  { key: "stripe",     label: "Stripe" },
  { key: "docker",     label: "Docker" },
  { key: "linux",      label: "Linux/Ubuntu" },
  { key: "threejs",    label: "Three.js" },
  { key: "html",       label: "HTML5" },
  { key: "css",        label: "CSS3" },
  { key: "figma",      label: "Figma" },
] as const;
